CREATE DATABASE osborne_michael_db;
USE osborne_michael_db;

CREATE TABLE TRACK (
	TrackID CHAR(36) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Shape VARCHAR(20) NULL,
	Distance DECIMAL(5,3) NULL,
	FrontStretch INTEGER NULL,
	Backstretch INTEGER NULL,
	State VARCHAR(20) NULL,
	Surface VARCHAR(20) NULL,
	TrackType VARCHAR(20) NULL,
	Owner VARCHAR(40) NULL,
	CONSTRAINT TRACK_PK PRIMARY KEY (TrackID)
	);
	
CREATE TABLE RACE (
	RaceID CHAR(36) NOT NULL,
	TrackID CHAR(36) NOT NULL,
	Name VARCHAR(40) NOT NULL,
	StartDateTime DATETIME NULL,
	ElapsedTime INTEGER NULL,
	Laps INTEGER NULL,
	Comments VARCHAR(200) NULL,
	LeadChanges INTEGER NULL,
	AverageSpeed DECIMAL(7,3) NULL,
	VictoryMargin DECIMAL(10,3) NULL,
	CONSTRAINT TRACK_PK PRIMARY KEY (RaceID),
	CONSTRAINT TRACK_Relationship FOREIGN KEY (TrackID)
		REFERENCES TRACK (TrackID)
	);

CREATE TABLE CAR (
	CarID CHAR(36) NOT NULL,
	`Number` INTEGER NOT NULL,
	CONSTRAINT CAR_PK PRIMARY KEY (CarID)
	);

CREATE TABLE DRIVER (
	DriverID CHAR(36) NOT NULL,
	Height INTEGER NOT NULL,
	RookieYear INTEGER NULL,
	Twitter VARCHAR(100) NULL,
	Gender VARCHAR(10) NULL,
	FirstName VARCHAR(30) NULL,
	LastName VARCHAR(30) NULL,
	CONSTRAINT DRIVER_PK PRIMARY KEY (DriverID)
	);

CREATE TABLE DRIVER_CAR_RELATIONSHIP (
	DriverID CHAR(36) NOT NULL,
	CarID CHAR(36) NOT NULL,
	CONSTRAINT DRIVER_CAR_RELATIONSHIP_PK PRIMARY KEY (DriverID, CarID),
	CONSTRAINT DRIVER_Relationship FOREIGN KEY (DriverID)
		REFERENCES DRIVER (DriverID),
	CONSTRAINT CAR_Relationship FOREIGN KEY (CarID)
		REFERENCES CAR (CarID)
	);


CREATE TABLE MANUFACTURER (
	ManufacturerID CHAR(36) NOT NULL,
	Name INTEGER NOT NULL,
	CONSTRAINT MANUFACTURER_PK PRIMARY KEY (ManufacturerID)
	);

CREATE TABLE MANUFACTURER_CAR_RELATIONSHIP (
	ManufacturerID CHAR(36) NOT NULL,
	CarID CHAR(36) NOT NULL,
	CONSTRAINT MANUFACTURER_CAR_RELATIONSHIP_PK PRIMARY KEY (ManufacturerID, CarID),
	CONSTRAINT MANUFACTURER_Relationship FOREIGN KEY (ManufacturerID)
		REFERENCES MANUFACTURER (ManufacturerID),
	CONSTRAINT CAR_Relationship4 FOREIGN KEY (CarID)
		REFERENCES CAR (CarID)
	);

CREATE TABLE TEAM (
	TeamID CHAR(36) NOT NULL,
	Name VARCHAR(40) NOT NULL,
	CONSTRAINT TEAM_PK PRIMARY KEY (TeamID)
	);

CREATE TABLE TEAM_CAR_RELATIONSHIP (
	TeamID CHAR(36) NOT NULL,
	CarID CHAR(36) NOT NULL,
	CONSTRAINT TEAM_CAR_RELATIONSHIP_PK PRIMARY KEY (TeamID, CarID),
	CONSTRAINT TEAM_Relationship1 FOREIGN KEY (TeamID)
		REFERENCES TEAM (TeamID),
	CONSTRAINT CAR_Relationship1 FOREIGN KEY (CarID)
		REFERENCES CAR (CarID)
	);

CREATE TABLE CAR_OWNER (
	OwnerID CHAR(36) NOT NULL,
	Name VARCHAR(40) NOT NULL,
	CONSTRAINT CAR_OWNER_PK PRIMARY KEY (OwnerID)
	);

CREATE TABLE CAR_OWNER_CAR_RELATIONSHIP (
	OwnerID CHAR(36) NOT NULL,
	CarID VARCHAR(40) NOT NULL,
	CONSTRAINT CAR_OWNER_CAR_RELATIONSHIP_PK PRIMARY KEY (OwnerID, CarID),
	CONSTRAINT CAR_OWNER_Relationship FOREIGN KEY (OwnerID)
		REFERENCES CAR_OWNER (OwnerID),
	CONSTRAINT CAR_Relationship2 FOREIGN KEY (CarID)
		REFERENCES CAR (CarID)
	);

CREATE TABLE `RESULT` (
	CarID CHAR(36) NOT NULL,
	RaceID CHAR(36) NOT NULL,
	StartPosition INTEGER NULL,
	FinishPosition INTEGER NULL,
	FinishStatus VARCHAR(20) NULL,
	BestLapSpeed DECIMAL(7,3) NULL,
	BestLapTime DECIMAL(7,3) NULL,
	FastestLap DECIMAL(7,3) NULL,
	Points INTEGER NULL,
	LapsCompleted INTEGER NULL,
	CONSTRAINT RESULT_PK PRIMARY KEY (RaceID, CarID),
	CONSTRAINT RACE_Relationship FOREIGN KEY (RaceID)
		REFERENCES RACE (RaceID),
	CONSTRAINT CAR_Relationship3 FOREIGN KEY (CarID)
		REFERENCES CAR (CarID)
	);


-- populate the tables
INSERT INTO Driver VALUES ("85c06960-3610-4eff-9ef2-18641b84c952", 73, 2004, "@kylebusch", "M", "Kyle", "Busch");
INSERT INTO Driver VALUES ("4d95ef3a-46cc-43c2-b340-c92cea2ed7f8", 71, 2004, "@MartinTruex_Jr", "M", "Martin", "Truex");
INSERT INTO Driver VALUES ("9d18716c-fd73-48d4-b3da-44228c767b84", 70, 2001, "@KevinHarvick", "M", "Kevin", "Harvick");
INSERT INTO Driver VALUES ("a756eefd-801d-4214-ab1b-0b595c21c37d", 66, 2013, "@KyleLarsonRacin", "M", "Kyle", "Larson");
INSERT INTO Driver VALUES ("0ce4113d-34c8-4272-b658-3b929238dbd3", 70, 2010, "@keselowski", "M", "Brad", "Keselowski");


	
